return {
   -- beat to appear   crossfade    path
   {   0.000,          false,       "dbk2/i-wanna-see-your-peacock.lua" },
   {  20.000,          false,       "paul/cool.jpg" },
   {  28.000,          true,        "doglover6262/Lucina.lua" },
   {  36.000,          true,        "dandelion21/dandelion.lua" },
   {  44.000,          true,        "Mey-Z Daisy/a turkey and a peacock in love.jpg" },
   {  52.000,          false,       "alex/peacock.lua" },
   {  68.000,          true,        "catsudawn/peacock/peacock.lua"},
   {  84.000,          true,        "bogo/peacocklef-.lua" },
   {  92.000,          true,        "silverwolfstar/peacock.lua" },
   { 100.000,          true,        "Mey-Z Daisy/peacock-o-lantern.jpg" },
   { 108.000,          true,        "bogo/mimi.jpg" },
   { 116.000,          true,        "mrbrownjeremy/Peacuckoo.mp4" },
   { 124.000,          true,        "Mey-Z Daisy/ascii-peacock.mp4" },
   { 132.00,           true,        "mrbrownjeremy/CyberPeacock.mp4" },
   { 140.000,          true,        "mrbrownjeremy/Peacuckoo2.mp4" },
   { 148.000,          true,        "Draner/archipelago-peacock.jpg" },
   { 156.000,          true,        "bogo/when they say theyve got that dawg in em.lua" },
   { 164.000,          true,        "brandon/peacock.jpg" },
   { 172.000,          true,        "catsudawn/pavo-lisa.jpg" },
   { 180.000,          true,        "teejusb/peacock.lua" },
   { 188.000,          true,        "yume-chan/TaroNuke-and-a-peacock-in-a-purikura-booth.lua" },
   { 196.000,          true,        "Chingching/peacock.lua"},
   { 204.000,          true,        "Forn/cross-stitch.jpg" },
   { 212.000,          true,        "paul/hey-guys/hey-guys.lua" },
   { 228.000,          true,        "dbk2/oot.mp4"},
   { 248.000,          true,        "dbk2/fight/fight.lua" },
   { 260.000,          true,        "group/group-montage.lua" },
   { 268.000,          true,        "mrbrownjeremy/Peacuckoo3.mp4" },
   { 278.000,          true,        "placeholder.png"}  -- credits
   -- { 278.000,       true,        "credits/credits.lua"
}